# Generated by Django 5.2.4 on 2025-07-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='El ID del usuario propietario del pendiente según la API.', verbose_name='ID de Usuario (API)')),
                ('api_id', models.IntegerField(help_text='El ID único del pendiente proveniente de la API.', unique=True, verbose_name='ID del Pendiente (API)')),
                ('title', models.CharField(help_text='El título o descripción del pendiente.', max_length=255, verbose_name='Título')),
                ('completed', models.BooleanField(default=False, help_text='Indica si el pendiente ha sido completado.', verbose_name='Completado')),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'ordering': ['api_id'],
            },
        ),
    ]
